from . import attendance
from . import payments
from . import postgres
from . import students
from . import subjects
from . import teachers
from . import tests
from . import statistics
from . import test_files